name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
env:
  FORCE_COLOR: 1
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  build-qemu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        node:
          - 16
        target:
          - linux/arm64
          - linux/amd64
          - linux/arm64
          - linux/ppc64le
          - linux/s390x
          - linux/386
          - linux/arm/v7
          - linux/arm/v6
        variant:
          - alpine3.15
    name: ${{ matrix.variant }} (node=${{ matrix.node }}, target=${{ matrix.target }})
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.host }}

      - name: Install dependencies
        run: yarn install --ignore-scripts

      - name: Add env vars
        shell: bash
        run: |
          echo "V=1" >> $GITHUB_ENV
          if [ "${{ matrix.target }}" = "x86" ]; then
            echo "TARGET=ia32" >> $GITHUB_ENV
          else
            echo "TARGET=${{ matrix.target }}" >> $GITHUB_ENV
          fi
      - name: Add Linux env vars
        run: |
          echo "CFLAGS=${CFLAGS:-} -include ../src/gcc-preinclude.h" >> $GITHUB_ENV
          echo "CXXFLAGS=${CXXFLAGS:-} -include ../src/gcc-preinclude.h" >> $GITHUB_ENV

      - name: Configure build
        run: yarn node-pre-gyp configure --target_arch=${{ env.TARGET }}

      - name: Build binaries
        run: yarn node-pre-gyp build --target_arch=${{ env.TARGET }}

      - name: Print binary info
        run: |
          ldd lib/binding/*/node_sqlite3.node
          echo "---"
          nm lib/binding/*/node_sqlite3.node | grep "GLIBC_" | c++filt || true
          echo "---"
          file lib/binding/napi-v*/*

      - name: Run tests
        run: yarn test

      - name: Package prebuilt binaries
        run: yarn node-pre-gyp package --target_arch=${{ env.TARGET }}

      - name: Upload binaries to commit artifacts
        uses: actions/upload-artifact@v3
        if: matrix.node == 16
        with:
          name: prebuilt-binaries
          path: build/stage/*/*
          retention-days: 7

      - name: Upload binaries to GitHub Release
        run: yarn node-pre-gyp-github publish
        if: matrix.node == 16
        env:
          NODE_PRE_GYP_GITHUB_TOKEN: ${{ github.token }}
